In [22]:
import nbsetup
import numpy as np
import ergodicpy as ep
import seaborn as sns

In [ ]:
np.array([np.ones(8)]).shape

In [15]:
ep.binr(observations=[[0,1],[1]], count=5)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [14]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [16]:
len([])

0

In [19]:
np.array([1,2,3,4]).size

4

In [48]:
[[np.ones(20),np.ones(10)],[np.ones(20),np.ones(10)]]

[[array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1.]),
  array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])],
 [array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1.]),
  array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])]]

In [49]:
np.hstack([[np.ones(20),np.ones(10)],[np.ones(20),np.ones(10)]])

array([array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
              1., 1., 1.])                                                       ,
       array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
       array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
              1., 1., 1.])                                                       ,
       array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])], dtype=object)

In [42]:
ep.shannon_entropy([0,1])

0.0