In [1]:
import nbsetup
import numpy as np
import seaborn as sns
import pandas as pd
import itertools
import ensemblepy as ep
import scipy as sp
import matplotlib.pyplot as plt
import time

In [9]:
dimensions = 2
steps = 200
datum = 100
data = np.random.uniform(0,1,(datum,dimensions))

In [10]:
tic = time.time()
ep.densities(data, steps=steps, ram_bound=True)
toc = time.time()
print(toc-tic)

0.679480791091919


In [11]:
tic = time.time()
ep.densities(data, steps=steps, ram_bound=False)
toc = time.time()
print(toc-tic)

19.980245113372803


In [ ]:
for i in range(1,4):
    data = np.random.uniform(0,1,(10,i))
    f = ep.densities(data, steps=10, ram_bound=False)
    t = ep.densities(data, steps=10, ram_bound=True)
    print(np.array_equal(f,t))

In [9]:
dimensions = 2
references = 2
datums = 3

In [10]:
ref = ep.dimspace(0,1,references,dimensions)
ref.shape, ref 

((4, 2),
 array([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]]))

In [14]:
data = np.arange(datums*dimensions).reshape((datums,dimensions))
data.shape, data

((3, 2),
 array([[0, 1],
        [2, 3],
        [4, 5]]))

In [15]:
bb = np.broadcast_to(ref, (datums,references**dimensions,dimensions))
bb.shape, bb

((3, 4, 2),
 array([[[0., 0.],
         [0., 1.],
         [1., 0.],
         [1., 1.]],
 
        [[0., 0.],
         [0., 1.],
         [1., 0.],
         [1., 1.]],
 
        [[0., 0.],
         [0., 1.],
         [1., 0.],
         [1., 1.]]]))

In [16]:
delt = np.moveaxis(bb, 0,1) - data
delt.shape, delt

((4, 3, 2),
 array([[[ 0., -1.],
         [-2., -3.],
         [-4., -5.]],
 
        [[ 0.,  0.],
         [-2., -2.],
         [-4., -4.]],
 
        [[ 1., -1.],
         [-1., -3.],
         [-3., -5.]],
 
        [[ 1.,  0.],
         [-1., -2.],
         [-3., -4.]]]))

In [16]:
# (references, datums)
app = np.apply_along_axis(np.linalg.norm, 2, delt)
app.shape, app

((100, 3),
 array([[1.        , 3.60555128, 6.40312424],
        [0.88888889, 3.51364184, 6.3167424 ],
        [0.77777778, 3.42287151, 6.2311444 ],
        [0.66666667, 3.33333333, 6.14636297],
        [0.55555556, 3.2451293 , 6.06243238],
        [0.44444444, 3.1583712 , 5.97938847],
        [0.33333333, 3.07318149, 5.89726867],
        [0.22222222, 2.98969423, 5.81611215],
        [0.11111111, 2.90805607, 5.73595978],
        [0.        , 2.82842712, 5.65685425],
        [1.0061539 , 3.54512359, 6.33430792],
        [0.89580642, 3.45160546, 6.24697458],
        [0.7856742 , 3.35915921, 6.16040723],
        [0.6758625 , 3.26787582, 6.07463864],
        [0.56655772, 3.17785548, 5.9897031 ],
        [0.45812285, 3.08920862, 5.90563656],
        [0.35136418, 3.00205691, 5.82247667],
        [0.248452  , 2.91653439, 5.74026282],
        [0.15713484, 2.83278862, 5.65903626],
        [0.11111111, 2.75098187, 5.57884009],
        [1.02439383, 3.48718996, 6.26670607],
        [0.91624569, 3.

In [17]:
# then get one per reference, which are the densities
ms = np.mean(app, axis=1)
references**dimensions==ms.shape[0], ms.shape, ms

(True,
 (100,),
 array([3.6695585 , 3.57309105, 3.47726456, 3.38212099, 3.28770575,
        3.19406804, 3.10126116, 3.00934287, 2.91837565, 2.82842712,
        3.62852847, 3.53146215, 3.43508022, 3.33945899, 3.24470543,
        3.15098934, 3.05863259, 2.9684164 , 2.88298657, 2.81364436,
        3.59276329, 3.49557931, 3.39924572, 3.30392555, 3.20987082,
        3.11750726, 3.02763119, 2.9418933 , 2.86388633, 2.80003195,
        3.56210923, 3.46520984, 3.36940198, 3.27494921, 3.18225192,
        3.09194898, 3.0051028 , 2.92349887, 2.84992354, 2.78767447,
        3.5363119 , 3.4399926 , 3.34502698, 3.25175947, 3.16068751,
        3.07254288, 2.98840192, 2.9097858 , 2.83860194, 2.77666247,
        3.51505862, 3.41950561, 3.32554681, 3.23357298, 3.14411654,
        3.05790047, 2.97588166, 2.89924759, 2.8292897 , 2.7670925 ,
        3.49801838, 3.40332407, 3.31041854, 3.21970551, 3.13170505,
        3.04707521, 2.96661613, 2.89123099, 2.82181441, 2.75906688,
        3.48487218, 3.39105862, 